project:
  type: website
  render:
    - "*.qmd"
    - "team/*.qmd"

website:
  title: "AusTraits"
  
  navbar:
    logo: images/austraits_hex.png
    left:
      - href: index.qmd
        text: Platform
      - href: index.html#access
        text: Access
      - href: portal.qmd
        text: Data portal
      - href: index.html#software
        text: Tools
      - text: About
        menu:
          - href: family.qmd
            text: The family
          - href: team/team-partners.qmd
            text: Team
          - href: history.qmd
            text: History
          - href: impact.qmd
            text: Impact
    right:
      - href: contribute.qmd
        text: Contribute
      - href: https://github.com/traitecoevo/austraits.org
        icon: github
        target: _blank

  search: 
    location: navbar


format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    include-after-body: _footer.html

editor: source

execute:
  freeze: auto
